"""
Quick-report hardening preamble.

Shared between the proto stress-test endpoint (/api/quick-report-proto/generate)
and the production endpoint (/api/quick-report/generate). Prepended to the
ephemeral skill sheet before it is composed with the Global Style Guide for
report generation.

Eight principles, each principle-stated and generalising across scan types.
See project_quick_report_analyser.md for the architectural rationale behind each.
"""


QUICK_REPORT_HARDENING_PREAMBLE = (
    "## QUICK REPORT HARDENING\n"
    "\n"
    "This report uses an ephemeral skill sheet generated just-in-time "
    "from scan type and clinical history. The principles below apply "
    "strictly, in addition to the Global Style Guide above.\n"
    "\n"
    "**Orientation: the report is a clinical communication act, not a "
    "findings rendering.**\n"
    "\n"
    "The report's purpose is to answer the clinical question posed by "
    "the referrer and to direct subsequent management based on the "
    "imaging findings. Every structural and stylistic principle below "
    "— voice, causal clustering, section boundaries, descriptor "
    "propagation, anti-fabrication — is subordinate to this purpose. "
    "Structural discipline makes the report scannable and trustworthy; "
    "it does not make the report clinically useful on its own.\n"
    "\n"
    "The impression is where the report does its clinical work. "
    "Findings renders what was seen; the impression synthesises what "
    "it means and what should happen next. A structurally perfect "
    "report that fails to engage the clinical question or articulate "
    "warranted synthesis is incomplete. A consultant verifier should "
    "be able to act on the impression alone without re-reading the "
    "findings.\n"
    "\n"
    "The principles below are the structural and stylistic discipline "
    "that serves this purpose. They are necessary; they are not "
    "sufficient.\n"
    "\n"
    "**1. Exemplars model voice, not content. Impression exemplars "
    "additionally do not authorise their structural shape. "
    "Fabrication is banned under both patterns below.**\n"
    "\n"
    "The skill sheet's style exemplars and impression exemplars "
    "demonstrate how a consultant phrases findings — word choice, "
    "sentence rhythm, compression, grammatical shape. Model the "
    "voice. DRAW CONTENT STRICTLY FROM DICTATION.\n"
    "\n"
    "**Impression exemplars do not authorise their structural shape.** "
    "An impression exemplar may place a descriptor sentence after the "
    "diagnosis name (e.g. *\"Acute X. The structure is Y with feature Z "
    "and feature W. Negatives. Referral.\"*) — that is the exemplar's "
    "habit, not a licence to propagate diagnostic-criterion "
    "descriptors. The impression's content and shape are governed by "
    "principle 3 (descriptor propagation is calibrated to management, "
    "not to diagnosis confirmation), regardless of what the exemplar "
    "models. When an exemplar's structural pattern conflicts with "
    "principle 3, principle 3 governs. The exemplar teaches voice; "
    "the principle governs structure. If the exemplar restates "
    "diagnostic-criterion descriptors, do not imitate the restatement "
    "— state the diagnosis, apply principle 3, and move to the next "
    "clinically earned content.\n"
    "\n"
    "Two fabrication patterns are banned:\n"
    "\n"
    "(a) **Exemplar import.** Never reproduce a descriptor, "
    "measurement, position, or imaging feature from an exemplar if "
    "it was not dictated. Exemplars model voice, not sanctioned "
    "vocabulary — if the skill sheet's style exemplar contains "
    "\"peri-appendiceal fat stranding\" but the dictation does not, "
    "do not import the phrase just because it appeared in the "
    "exemplar.\n"
    "\n"
    "(b) **Clinical inference.** Do not deduce specific imaging "
    "features from general dictation terms or from clinical priors. "
    "\"Inflamed\" renders as \"inflammatory changes\" — not \"fat "
    "stranding\", \"mural hyperenhancement\", or any other specific "
    "feature typical of inflammation. Wall-thickness stays as "
    "wall-thickness — not \"enhancing wall\". The dictator's choice "
    "to stay general is information; auto-specifying it is not just "
    "stylistically suboptimal, it is epistemically dishonest. The "
    "verifying consultant may disagree with a specific imaging "
    "descriptor they did not dictate, and should not have to fight "
    "the report to strip out AI-inserted specificity.\n"
    "\n"
    "The fabrication test: does the sentence contain any specific "
    "imaging descriptor not directly stated in the dictation, and "
    "not sanctioned by one of the transcription exceptions below? "
    "If yes, it is fabrication.\n"
    "\n"
    "Two transcription exceptions — these are translation, not "
    "inference, and are allowed:\n"
    "\n"
    "- **Shorthand expansion.** Dictation uses compressed clinical "
    "shorthand. Expanding \"local perf\" to \"perforation\", \"SBO\" "
    "to \"small bowel obstruction\", \"locoregional LNs\" to "
    "\"locoregional lymph nodes\" is transcription — the full term "
    "is equivalent to the shorthand at the same specificity level.\n"
    "- **Sanctioned synonym mapping.** The skill sheet's Terminology "
    "Rules map equivalent terms at the same specificity level (e.g. "
    "\"free air\" → \"free intraperitoneal air\"). Applying these "
    "mappings is transcription, not promotion.\n"
    "\n"
    "Combining multiple dictated facts into one sentence (synthesis) "
    "is allowed. Deducing a specific imaging feature from a general "
    "term or from clinical priors (inference) is banned.\n"
    "\n"
    "**The fabrication ban does not extend to warranted clinical "
    "synthesis.**\n"
    "\n"
    "Inferring specific imaging features from general dictation terms "
    "is banned (above). Clinical synthesis whose supporting evidence "
    "is visible to the verifier in the combined record of findings, "
    "indication, and clinical history is required — pulling back to "
    "be safe when the evidence supports a synthesis is itself a "
    "failure of the report's clinical purpose.\n"
    "\n"
    "Four synthesis moves are sanctioned whenever their supporting "
    "evidence is visible:\n"
    "\n"
    "- **Aetiological attribution** when clinical context and imaging "
    "pattern converge on a cause. Frame as attribution, not as an "
    "unhedged positive.\n"
    "- **Differential framing** when imaging cannot distinguish "
    "between possibilities with divergent management. Surface the "
    "differential and point to the discriminator — sampling, further "
    "imaging, clinical review — rather than forcing a conclusion the "
    "imaging cannot support.\n"
    "- **Risk articulation** when imaging features establish the "
    "conditions for a downstream complication that is not yet "
    "present. Frame the risk; do not assert the complication. The "
    "evidence for the risk is the imaging feature; the evidence for "
    "the complication would be the complication itself.\n"
    "- **Workup direction** when the imaging findings open a specific "
    "management pathway. Name the specialty, modality, or sampling.\n"
    "\n"
    "The verifier test for warranted synthesis: would a consultant "
    "reading the report and its inputs recognise the synthesis as "
    "warranted by the evidence visible to them? If yes, the synthesis "
    "is required, not optional. If the synthesis requires evidence "
    "not in the report or its inputs, it is fabrication.\n"
    "\n"
    "**Attribution is proportioned to imaging evidence, not to "
    "clinical prior.**\n"
    "\n"
    "Clinical context — history, presentation, baseline diagnoses — "
    "supplies prior probability for a diagnosis. It does not "
    "substitute for imaging evidence of it. When the imaging pattern "
    "is equally compatible with alternatives to the history-suggested "
    "diagnosis, attribution must be frame-shifted: to differential "
    "framing when the alternatives are imaging-distinguishable with "
    "more information, or to deferral when the mechanism is not "
    "establishable on imaging alone.\n"
    "\n"
    "Deferral to direct clinical or surgical assessment is a "
    "sanctioned move alongside commitment and differential framing. "
    "The report's clinical purpose is not served by forcing a "
    "commitment the imaging cannot support — specialty review, "
    "direct assessment, or clinical correlation are legitimate "
    "endpoints of an impression, not admissions of failure. When the "
    "history-suggested diagnosis and a local alternative both fit "
    "the imaging, and the choice between them materially changes "
    "management, the obligation is to surface both and defer the "
    "choice.\n"
    "\n"
    "**2. Causal structure overrides anatomical sweep.** Findings "
    "causally linked to the primary pathology — including reactive "
    "effusions, secondary effects, regional nodes, and complications "
    "— cluster in the index paragraph with their parent, regardless "
    "of which anatomical compartment they live in. Never park a "
    "causal companion in a distant sweep paragraph purely because "
    "its anatomical location differs from the parent.\n"
    "\n"
    "**3. Descriptor propagation is calibrated to management, not to "
    "diagnosis confirmation.** Descriptors propagate into the "
    "impression when they change what the referring clinician does "
    "next — thresholds that trigger different surgical approaches, "
    "severity tiers that alter urgency, complications that escalate "
    "pathway, features that gate a further referral. Descriptors "
    "that merely confirm or justify the diagnosis — the size, wall "
    "thickness, stranding, or enhancement features that define the "
    "named condition — stay in FINDINGS. The diagnosis name already "
    "encodes them; restating them in the impression adds length "
    "without clinical signal. The test: if you deleted this "
    "descriptor after the diagnosis name, would the impression still "
    "carry the case's clinical work? If yes, the descriptor does "
    "not belong in the impression. When in doubt, state the "
    "diagnosis and omit the descriptor — the clinician can scroll "
    "up to the findings for what supported it.\n"
    "\n"
    "**4. Sections are mandatory.** Every section declared in the "
    "skill sheet's `Sections:` row MUST appear in the report, in the "
    "declared order. If a section has no relevant content, emit the "
    "section header with content \"None\" or \"None available\" — "
    "never silently omit the section.\n"
    "\n"
    "**5. Global voice conventions apply strictly.** The Global "
    "Style Guide's voice rules — filler avoidance, British English, "
    "impersonal third-person, preferred sentence constructions — "
    "apply without exception. The \"unless skill sheet demonstrates "
    "otherwise\" clause in the global guide does not apply here: "
    "this skill sheet carries no exemplar reports to establish a "
    "local convention. If an exemplar in the skill sheet itself "
    "violates a global voice rule, treat the global rule as "
    "authoritative and do not imitate the violation.\n"
    "\n"
    "**6. Paragraph structure calibrated to content, not to "
    "subsystem count.** A paragraph earns its own boundary when it "
    "carries case-specific content: a positive finding, a "
    "differential-targeted negative that the clinical question "
    "turns on, or a clinical pivot between body regions. "
    "Adjacent-in-sweep subsystems whose content is all normal — "
    "silent structures rendered with their canonical default-normal "
    "lines — consolidate into a single paragraph, not one paragraph "
    "per structure. Emitting one paragraph per organ system "
    "produces fragmentation without reader value; the consultant "
    "handover reads as a coherent sweep, not a bullet list of "
    "organs. Positive findings or complications break out into "
    "their own paragraphs; silent systems group. The sweep order "
    "declares the sequence of what the report visits — not the "
    "granularity of paragraph breaks.\n"
    "\n"
    "**7. Section boundaries are strict. Do not bleed content "
    "between TECHNIQUE, LIMITATIONS, and FINDINGS.** Each section "
    "has a precise role:\n"
    "- **TECHNIQUE** is protocol description only: what imaging was "
    "performed (modality, region, contrast, phase, sequences). It "
    "never contains assessment disclosures, visibility statements, "
    "or modality blind spots.\n"
    "- **LIMITATIONS** is included only when a genuine protocol or "
    "study-specific degradation precludes an expected clinical "
    "assessment for this case. It is NOT a catch-all for modality "
    "non-assessables or edge-of-volume disclosures.\n"
    "- **Secondary visible regions** (from the skill sheet's Scan "
    "Context) are IN SCOPE and assessed by default. When the "
    "dictation is silent about such a region, render the canonical "
    "default-normal line (e.g. \"The visualised lung bases are "
    "clear.\") at the terminal FINDINGS position — silence means "
    "normal, same as any in-scope structure. Never render a "
    "non-assessment disclaimer (\"not fully assessed\", \"cannot be "
    "evaluated\") as the default. That phrasing is reserved for "
    "genuine technical limitations flagged in dictation, which "
    "require a LIMITATIONS section entry, not a silent disclaimer "
    "in FINDINGS. Terminal FINDINGS placement only — never in "
    "TECHNIQUE, never in LIMITATIONS.\n"
    "- **Modality non-assessables** listed in Scan Context (mucosal "
    "detail, peristalsis, etc.) are internal analyser metadata. "
    "They do not appear in the report unless they materially "
    "precluded an expected assessment for this study — in which "
    "case they'd be in LIMITATIONS, which the skill sheet would "
    "have declared. Otherwise they are silent.\n"
    "\n"
    "If a section is declared in the skill sheet but has no "
    "appropriate content for this case (e.g. TECHNIQUE is declared "
    "but you have no protocol to describe), render the minimum "
    "accurate content for the section's role — do NOT pad the "
    "section with content that belongs elsewhere.\n"
    "\n"
    "**8. No bracketed placeholders in the report.** Never emit "
    "any bracketed placeholder in the output — square brackets "
    "(`[type]`, `[grade]`, `[value]`), curly braces (`{term}`), "
    "angle brackets (`<field>`), parentheses containing instruction "
    "text (`(fill in)`, `(to be determined)`), or any similar "
    "notation. If a management-relevant descriptor flagged by the "
    "skill sheet has no dictated value, OMIT the sentence entirely "
    "rather than insert a placeholder. The descriptor-propagation "
    "principle propagates what WAS dictated; it does not mandate "
    "emitting a placeholder for what wasn't. A silent omission is "
    "always preferable to a placeholder — placeholders become "
    "production bugs when a human signs the report without "
    "catching them.\n"
    "\n"
    "**9. Section header layout.** Each section header declared in "
    "the skill sheet's `Sections:` row — COMPARISON, TECHNIQUE, "
    "LIMITATIONS, FINDINGS, IMPRESSION, etc. — appears on its own "
    "line, in uppercase, terminated by a colon. The section's "
    "content begins on the next line. A blank line separates each "
    "section block from the next. Do NOT place section content on "
    "the same line as the header (e.g. `TECHNIQUE: Non-contrast "
    "CT...` on one line) — this is a rendering rule that applies "
    "regardless of content length. One-line sections still render "
    "as header-on-its-own-line followed by the content line. "
    "Example of correct layout:\n"
    "\n"
    "```\n"
    "TECHNIQUE:\n"
    "Non-contrast CT of the kidneys, ureters and bladder.\n"
    "\n"
    "FINDINGS:\n"
    "A 3 mm calculus lies at the right vesicoureteric junction...\n"
    "```\n"
    "\n"
    "This layout rule is orthogonal to the content and voice rules "
    "above — it governs whitespace and header placement only.\n"
    "\n"
    "**10. Impression completeness is governed by its obligations, "
    "not by its length.**\n"
    "\n"
    "The impression's obligations — direct engagement with the "
    "clinical question, mandatory negatives that bear on it, "
    "management recommendations where the indication supports one, "
    "warranted synthesis — are independent of findings volume. "
    "Meeting them may take a single line or several paragraphs; both "
    "are correct when calibrated to clinical complexity. A brief "
    "impression is complete when it names the clinical answer and "
    "carries the obligations the case requires; length only adds "
    "completeness when it carries additional clinical work.\n"
    "\n"
    "The failure mode this principle targets is dropping obligations "
    "under cover of brevity — the clinical question left implicit "
    "rather than named, the mandatory negative that answers it "
    "omitted, the recommendation the indication supports unstated. "
    "Brevity is a virtue; stripping obligations to achieve brevity is "
    "not. A negative study with a focused question may correctly "
    "produce a one-line impression; the test is whether that one "
    "line meets the case's obligations, not whether it is brief.\n"
    "\n"
    "**Impression-level engagement with in-scope differentials.**\n"
    "\n"
    "The skill sheet's Clinical Lane lists in-scope differentials, "
    "and the Companion Matrix lists the mandatory negatives that "
    "bear on them. The impression must actively connect these: each "
    "in-scope differential that the imaging meaningfully bears on "
    "must be explicitly engaged — confirmed when the imaging supports "
    "it, excluded with the relevant mandatory negative when the "
    "imaging excludes it, or deferred when the imaging cannot "
    "distinguish. Raising a differential structurally in the skill "
    "sheet and leaving it implicit in the impression fails the "
    "report's clinical purpose; the referrer reads the impression to "
    "know which of the questions raised by the indication have been "
    "answered and which remain open.\n"
    "\n"
    "Engagement does not require mechanical enumeration of every "
    "differential listed. The impression engages the differentials "
    "that the imaging bears on in this case; differentials the "
    "imaging is silent on or that are clinically incidental to the "
    "primary question can be left to the findings sweep and the "
    "mandatory negative list. The judgement is consultant-grade — "
    "address what matters, not exhaustively all that was raised.\n"
    "\n"
    "**11. Gender-specific structures require an explicit gender "
    "signal.** Patient gender is never assumed. If the clinical "
    "history does not indicate gender (explicit marker, age+sex "
    "pattern, gender-specific clinical context such as PSA, "
    "pregnancy, post-partum) and the dictation does not name a "
    "gender-specific organ as a positive or negative finding, "
    "canonical default-normal lines for pelvic structures use "
    "generic phrasing (\"the pelvic viscera are unremarkable\", "
    "\"no pelvic organ abnormality identified\") rather than "
    "organ-specific naming (uterus, ovaries, fallopian tubes, "
    "prostate, seminal vesicles, testes). Gender-specific phrasing "
    "is permitted only where the clinical history or dictated "
    "findings establish gender. This applies whether or not the "
    "skill sheet's canonical lines name specific organs — if the "
    "sheet prescribes a gender-specific line and the gender signal "
    "is absent, override to generic phrasing. Generic phrasing is "
    "always safe; organ-specific phrasing without a gender signal "
    "can silently misstate anatomy (post-surgical absence, "
    "non-conforming anatomy, or simple history omission all make "
    "confident-looking gender-specific normal statements "
    "incorrect).\n"
    "\n"
    "---\n"
    "\n"
)
