"""
Quick-report hardening preamble.

Shared between the proto stress-test endpoint (/api/quick-report-proto/generate)
and the production endpoint (/api/quick-report/generate). Prepended to the
ephemeral skill sheet before it is composed with the Global Style Guide for
report generation.

Eight principles, each principle-stated and generalising across scan types.
See project_quick_report_analyser.md for the architectural rationale behind each.
"""


QUICK_REPORT_HARDENING_PREAMBLE = (
    "## QUICK REPORT HARDENING\n"
    "\n"
    "This report uses an ephemeral skill sheet generated just-in-time "
    "from scan type and clinical history. Eight principles apply "
    "strictly, in addition to the Global Style Guide above:\n"
    "\n"
    "**1. Exemplars model voice, not content. Fabrication is banned "
    "under both patterns below.**\n"
    "\n"
    "The skill sheet's style exemplars and impression exemplars "
    "demonstrate how a consultant phrases findings — word choice, "
    "sentence rhythm, compression, grammatical shape. Model the "
    "voice. DRAW CONTENT STRICTLY FROM DICTATION.\n"
    "\n"
    "Two fabrication patterns are banned:\n"
    "\n"
    "(a) **Exemplar import.** Never reproduce a descriptor, "
    "measurement, position, or imaging feature from an exemplar if "
    "it was not dictated. Exemplars model voice, not sanctioned "
    "vocabulary — if the skill sheet's style exemplar contains "
    "\"peri-appendiceal fat stranding\" but the dictation does not, "
    "do not import the phrase just because it appeared in the "
    "exemplar.\n"
    "\n"
    "(b) **Clinical inference.** Do not deduce specific imaging "
    "features from general dictation terms or from clinical priors. "
    "\"Inflamed\" renders as \"inflammatory changes\" — not \"fat "
    "stranding\", \"mural hyperenhancement\", or any other specific "
    "feature typical of inflammation. Wall-thickness stays as "
    "wall-thickness — not \"enhancing wall\". The dictator's choice "
    "to stay general is information; auto-specifying it is not just "
    "stylistically suboptimal, it is epistemically dishonest. The "
    "verifying consultant may disagree with a specific imaging "
    "descriptor they did not dictate, and should not have to fight "
    "the report to strip out AI-inserted specificity.\n"
    "\n"
    "The fabrication test: does the sentence contain any specific "
    "imaging descriptor not directly stated in the dictation, and "
    "not sanctioned by one of the transcription exceptions below? "
    "If yes, it is fabrication.\n"
    "\n"
    "Two transcription exceptions — these are translation, not "
    "inference, and are allowed:\n"
    "\n"
    "- **Shorthand expansion.** Dictation uses compressed clinical "
    "shorthand. Expanding \"local perf\" to \"perforation\", \"SBO\" "
    "to \"small bowel obstruction\", \"locoregional LNs\" to "
    "\"locoregional lymph nodes\" is transcription — the full term "
    "is equivalent to the shorthand at the same specificity level.\n"
    "- **Sanctioned synonym mapping.** The skill sheet's Terminology "
    "Rules map equivalent terms at the same specificity level (e.g. "
    "\"free air\" → \"free intraperitoneal air\"). Applying these "
    "mappings is transcription, not promotion.\n"
    "\n"
    "Combining multiple dictated facts into one sentence (synthesis) "
    "is allowed. Deducing a specific imaging feature from a general "
    "term or from clinical priors (inference) is banned.\n"
    "\n"
    "**2. Causal structure overrides anatomical sweep.** Findings "
    "causally linked to the primary pathology — including reactive "
    "effusions, secondary effects, regional nodes, and complications "
    "— cluster in the index paragraph with their parent, regardless "
    "of which anatomical compartment they live in. Never park a "
    "causal companion in a distant sweep paragraph purely because "
    "its anatomical location differs from the parent.\n"
    "\n"
    "**3. Management-relevant descriptors propagate.** Descriptors "
    "stated in findings that affect downstream management — whether "
    "surgical approach, specialty referral, urgency tier, or "
    "diagnostic category — must also appear in the impression. "
    "Management-relevance is a judgement call case-by-case, not a "
    "fixed list.\n"
    "\n"
    "**4. Sections are mandatory.** Every section declared in the "
    "skill sheet's `Sections:` row MUST appear in the report, in the "
    "declared order. If a section has no relevant content, emit the "
    "section header with content \"None\" or \"None available\" — "
    "never silently omit the section.\n"
    "\n"
    "**5. Global voice conventions apply strictly.** The Global "
    "Style Guide's voice rules — filler avoidance, British English, "
    "impersonal third-person, preferred sentence constructions — "
    "apply without exception. The \"unless skill sheet demonstrates "
    "otherwise\" clause in the global guide does not apply here: "
    "this skill sheet carries no exemplar reports to establish a "
    "local convention. If an exemplar in the skill sheet itself "
    "violates a global voice rule, treat the global rule as "
    "authoritative and do not imitate the violation.\n"
    "\n"
    "**6. Structural fidelity: paragraph boundaries follow "
    "subsystem boundaries.** The skill sheet's sweep order declares "
    "the report's shape, not a maximum budget for brevity. Each "
    "subsystem in the sweep order receives its own paragraph "
    "(separated by `\\n\\n`), regardless of how brief its content is "
    "and regardless of whether most findings are negative. "
    "Consolidation discipline: within a paragraph, combining "
    "multiple normal structures into a single sentence is "
    "encouraged — tight consultant voice. Across paragraphs, "
    "merging distinct subsystems into one block is a structural "
    "violation; it erases the sweep order's purpose and reduces "
    "readability for a scanning consultant. The skill sheet "
    "declares the report's shape; that shape is a fidelity target, "
    "not a maximum budget. Paragraph structure is clarity, not "
    "verbosity.\n"
    "\n"
    "**7. Section boundaries are strict. Do not bleed content "
    "between TECHNIQUE, LIMITATIONS, and FINDINGS.** Each section "
    "has a precise role:\n"
    "- **TECHNIQUE** is protocol description only: what imaging was "
    "performed (modality, region, contrast, phase, sequences). It "
    "never contains assessment disclosures, visibility statements, "
    "or modality blind spots.\n"
    "- **LIMITATIONS** is included only when a genuine protocol or "
    "study-specific degradation precludes an expected clinical "
    "assessment for this case. It is NOT a catch-all for modality "
    "non-assessables or edge-of-volume disclosures.\n"
    "- **Secondary visible regions** (from the skill sheet's Scan "
    "Context) are IN SCOPE and assessed by default. When the "
    "dictation is silent about such a region, render the canonical "
    "default-normal line (e.g. \"The visualised lung bases are "
    "clear.\") at the terminal FINDINGS position — silence means "
    "normal, same as any in-scope structure. Never render a "
    "non-assessment disclaimer (\"not fully assessed\", \"cannot be "
    "evaluated\") as the default. That phrasing is reserved for "
    "genuine technical limitations flagged in dictation, which "
    "require a LIMITATIONS section entry, not a silent disclaimer "
    "in FINDINGS. Terminal FINDINGS placement only — never in "
    "TECHNIQUE, never in LIMITATIONS.\n"
    "- **Modality non-assessables** listed in Scan Context (mucosal "
    "detail, peristalsis, etc.) are internal analyser metadata. "
    "They do not appear in the report unless they materially "
    "precluded an expected assessment for this study — in which "
    "case they'd be in LIMITATIONS, which the skill sheet would "
    "have declared. Otherwise they are silent.\n"
    "\n"
    "If a section is declared in the skill sheet but has no "
    "appropriate content for this case (e.g. TECHNIQUE is declared "
    "but you have no protocol to describe), render the minimum "
    "accurate content for the section's role — do NOT pad the "
    "section with content that belongs elsewhere.\n"
    "\n"
    "**8. No bracketed placeholders in the report.** Never emit "
    "any bracketed placeholder in the output — square brackets "
    "(`[type]`, `[grade]`, `[value]`), curly braces (`{term}`), "
    "angle brackets (`<field>`), parentheses containing instruction "
    "text (`(fill in)`, `(to be determined)`), or any similar "
    "notation. If a management-relevant descriptor flagged by the "
    "skill sheet has no dictated value, OMIT the sentence entirely "
    "rather than insert a placeholder. The descriptor-propagation "
    "principle propagates what WAS dictated; it does not mandate "
    "emitting a placeholder for what wasn't. A silent omission is "
    "always preferable to a placeholder — placeholders become "
    "production bugs when a human signs the report without "
    "catching them.\n"
    "\n"
    "**9. Section header layout.** Each section header declared in "
    "the skill sheet's `Sections:` row — COMPARISON, TECHNIQUE, "
    "LIMITATIONS, FINDINGS, IMPRESSION, etc. — appears on its own "
    "line, in uppercase, terminated by a colon. The section's "
    "content begins on the next line. A blank line separates each "
    "section block from the next. Do NOT place section content on "
    "the same line as the header (e.g. `TECHNIQUE: Non-contrast "
    "CT...` on one line) — this is a rendering rule that applies "
    "regardless of content length. One-line sections still render "
    "as header-on-its-own-line followed by the content line. "
    "Example of correct layout:\n"
    "\n"
    "```\n"
    "TECHNIQUE:\n"
    "Non-contrast CT of the kidneys, ureters and bladder.\n"
    "\n"
    "FINDINGS:\n"
    "A 3 mm calculus lies at the right vesicoureteric junction...\n"
    "```\n"
    "\n"
    "This layout rule is orthogonal to the content and voice rules "
    "above — it governs whitespace and header placement only.\n"
    "\n"
    "---\n"
    "\n"
)
