"""Database module for Rapid Reports AI"""

from .connection import get_db, SessionLocal, engine
from .models import Base, Template, User, PasswordResetToken, Report, TemplateVersion, ReportVersion, ReportAudit, ReportAuditCriterion, TnmStaging, EphemeralSkillSheet
from .crud import (
    # User CRUD
    create_user,
    get_user_by_email,
    get_user_by_id,
    update_last_login,
    # Password Reset Token CRUD
    create_reset_token,
    get_valid_reset_token,
    mark_token_used,
    # Template CRUD
    create_template,
    get_template,
    get_templates,
    update_template,
    delete_template,
    get_all_tags,
    rename_tag,
    delete_tag,
    # Template Version CRUD
    create_template_version,
    get_template_versions,
    get_template_version,
    restore_template_version,
    increment_template_usage,
    get_current_version_id,
    delete_template_version,
    toggle_template_pin,
    # Report CRUD
    create_report,
    get_report,
    get_user_reports,
    delete_report,
    create_report_version,
    get_report_versions,
    get_report_version,
    set_current_report_version,
    # Validation Status CRUD
    update_validation_status,
    get_validation_status,
    # Audit CRUD
    create_report_audit,
    append_audit_criteria,
    get_report_audits,
    acknowledge_criterion,
    # Ephemeral Skill Sheet CRUD (quick-report-ephemeral pipeline)
    create_ephemeral_skill_sheet,
    get_ephemeral_skill_sheet,
    create_quick_report_with_candidates,
    set_quick_report_selection,
)

# Export Base so it can be imported from database module
__all__ = [
    "get_db",
    "SessionLocal",
    "engine",
    "Base",
    "Template",
    "User",
    "PasswordResetToken",
    "Report",
    "TemplateVersion",
    "ReportVersion",
    "create_user",
    "get_user_by_email",
    "get_user_by_id",
    "update_last_login",
    "create_reset_token",
    "get_valid_reset_token",
    "mark_token_used",
    "create_template",
    "get_template",
    "get_templates",
    "update_template",
    "delete_template",
    "get_all_tags",
    "rename_tag",
    "delete_tag",
    "create_template_version",
    "get_template_versions",
    "get_template_version",
    "restore_template_version",
    "increment_template_usage",
    "get_current_version_id",
    "delete_template_version",
    "toggle_template_pin",
    "create_report",
    "get_report",
    "get_user_reports",
    "delete_report",
    "create_report_version",
    "get_report_versions",
    "get_report_version",
    "set_current_report_version",
    "update_validation_status",
    "get_validation_status",
    "ReportAudit",
    "ReportAuditCriterion",
    "TnmStaging",
    "create_report_audit",
    "get_report_audits",
    "append_audit_criteria",
    "acknowledge_criterion",
    # Ephemeral Skill Sheet pipeline
    "EphemeralSkillSheet",
    "create_ephemeral_skill_sheet",
    "get_ephemeral_skill_sheet",
    "create_quick_report_with_candidates",
    "set_quick_report_selection",
]

